name: Build and test code
on: [push, pull_request]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        golang-version: [1.20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup golang v${{ matrix.golang-version }}
        uses: actions/setup-go@v2
        with:
          go-version: "^${{ matrix.golang-version }}"
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ matrix.os }}-${{ matrix.golang-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.golang-version }}-go-
      - run: mkdir cmd/test_artifacts
      - run: go test -v ./...
